#pragma once
#include <Windows.h>

constexpr UINT PER_VERTEX_SLOT = 0;

constexpr UINT VIEW_BUFFER_SLOT = 0;

constexpr UINT MATERIAL_BUFFER_SLOT = 1;

constexpr UINT DIRECTIONAL_LIGHT_SLOT = 2;

constexpr UINT TEXTURE_FLAGS_SLOT = 3;

constexpr UINT SAMPLER_SLOT = 4;
constexpr UINT DIFFUSE_TEXTURE_SLOT = 4;
constexpr UINT SPECULAR_TEXTURE_SLOT = 5;
constexpr UINT AMBIENT_TEXTURE_SLOT = 6;
constexpr UINT EMISSIVE_TEXTURE_SLOT = 7;
constexpr UINT NORMAL_TEXTURE_SLOT = 8;
constexpr UINT BUMP_TEXTURE_SLOT = 9;
constexpr UINT DISPLACEMENT_TEXTURE_SLOT = 10;
constexpr UINT STENCIL_DECA_TEXTURE_SLOT = 11;
constexpr UINT REFLECTION_TEXTURE_SLOT = 12;
constexpr UINT SHININESS_TEXTURE_SLOT = 13;
constexpr UINT ALPHA_TEXTURE_SLOT = 14;